### ISSUE TITLE
mouse and keyboard are not working after reboot (pikvm-x86)

### ISSUE THREAD

**Issue by reproducepark** [srepac/kvmd-armbian#5]
I finished following your instruction for x86 today and this works pretty well. I applauded your wonderful project.

I connected a normal desktop pc to the n100 mini pc and it works fine on both bios and windows screens. However, after I reboot the desktop pc, the screen displays properly, but only mouse and keyboard are disabled. 

I checked the log.
[2024-09-16 11:14:14 kvmd.service] --- kvmd.plugins.hid.ch9329           INFO --- Too short response, HID might be disconnected
You will still see these messages.

I've tried changing the cable set as well, and I've also tried changing the location of the usb, but it's not solved. I need to reboot the mini pc running pikvm only to fix the problem.

**Comment by srepac** [comment]
You should go to my Discord and post in #support
