### ISSUE TITLE
No dwc2 module on Armbian Bookworm

### ISSUE THREAD

**Issue by outermedia-cbo** [srepac/kvmd-armbian#6]
I am running kvmd on an Orange Pi Zero. It should support OTG (and it worked in the past). 

Now there is no dwc2 module anymore.

Does anyone have an idea how to get the dwc2 module?

**Comment by srepac** [comment]
Go ask your question at Discord https://discord.gg/YaJ87sVznc  I have an orange pi zero on armbian bookworm and it works just fine.

**Comment by srepac** [comment]
[root@opz2 ~]# cat /etc/os-release
PRETTY_NAME="Armbian 24.5.5 bookworm"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.armbian.com"
SUPPORT_URL="https://forum.armbian.com"
BUG_REPORT_URL="https://www.armbian.com/bugs"
ARMBIAN_PRETTY_NAME="Armbian 24.5.5 bookworm"

[root@opz2 ~]# cat /boot/armbianEnv.txt
verbosity=1
bootlogo=false
console=both
disp_mode=1280x720p60
overlay_prefix=sun8i-h3
overlays=i2c0 i2c1 i2c2 usbhost2 usbhost3 tve
#rootdev=UUID=fce298d7-c775-4ec9-81e2-3f4b9b95dae8
rootdev=/dev/mmcblk0p1
rootfstype=ext4
usbstoragequirks=0x2537:0x1066:u,0x2537:0x1068:u

[root@opz2 ~]# ls -l /dev/kvmd*
lrwxrwxrwx 1 root root 5 May 29 10:41 /dev/kvmd-hid-keyboard -> hidg0
lrwxrwxrwx 1 root root 5 May 29 10:41 /dev/kvmd-hid-mouse -> hidg1
lrwxrwxrwx 1 root root 5 May 29 10:41 /dev/kvmd-hid-mouse-alt -> hidg2
lrwxrwxrwx 1 root root 6 May 29 10:41 /dev/kvmd-video -> video0

[root@opz2 ~]# apt-mark showhold
linux-dtb-current-sunxi
linux-image-current-sunxi

[root@opz2 ~]# pistat
# Xunlong Orange Pi Zero 256MB

**Comment by outermedia-cbo** [comment]
I switched to `linux-image-legacy-sunxi`. Now it works again. The `dwc2` module is still not present, so apparently it is not required. 

Thank you for updating the discord link! 

```
# uname -a
Linux orangepizero 6.1.104-legacy-sunxi #1 SMP Sun Aug 11 10:36:02 UTC 2024 armv7l GNU/Linux
```

```
# cat /etc/os-release 
PRETTY_NAME="Armbian 24.8.2 bookworm"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.armbian.com"
SUPPORT_URL="https://forum.armbian.com"
BUG_REPORT_URL="https://www.armbian.com/bugs"
ARMBIAN_PRETTY_NAME="Armbian 24.8.2 bookworm"
```

```
# lsmod 
Module                  Size  Used by
usb_f_hid              20480  9
sunrpc                339968  1
lz4hc                  16384  0
lz4hc_compress         24576  1 lz4hc
xradio_wlan           114688  0
lz4                    16384  0
lz4_compress           32768  1 lz4
mac80211              606208  1 xradio_wlan
uvcvideo               81920  1
videobuf2_vmalloc      20480  1 uvcvideo
videobuf2_memops       20480  1 videobuf2_vmalloc
videobuf2_v4l2         20480  1 uvcvideo
videobuf2_common       45056  4 uvcvideo,videobuf2_vmalloc,videobuf2_memops,videobuf2_v4l2
snd_usb_audio         212992  0
snd_hwdep              16384  1 snd_usb_audio
videodev              167936  4 uvcvideo,videobuf2_common,videobuf2_v4l2
snd_usbmidi_lib        28672  1 snd_usb_audio
snd_rawmidi            28672  1 snd_usbmidi_lib
cfg80211              577536  2 mac80211,xradio_wlan
snd_seq_device         16384  1 snd_rawmidi
sun4i_gpadc_iio        16384  0
mc                     40960  5 uvcvideo,snd_usb_audio,videobuf2_common,videodev,videobuf2_v4l2
industrialio           61440  1 sun4i_gpadc_iio
sun8i_thermal          16384  0
rfkill                 20480  2 cfg80211
libarc4                16384  1 mac80211
zram                   24576  3
cpufreq_dt             20480  0
binfmt_misc            20480  1
uio_pdrv_genirq        20480  0
uio                    16384  1 uio_pdrv_genirq
libcomposite           45056  12 usb_f_hid
dm_mod                 98304  0
ip_tables              24576  0
x_tables               28672  1 ip_tables
autofs4                36864  2
ac200_phy              16384  1
dwmac_sun8i            28672  0
lima                   49152  0
stmmac_platform        24576  1 dwmac_sun8i
stmmac                172032  2 stmmac_platform,dwmac_sun8i
gpu_sched              28672  1 lima
pwrseq_simple          16384  1
drm_shmem_helper       16384  1 lima
pcs_xpcs               20480  1 stmmac
phylink                36864  2 pcs_xpcs,stmmac
mdio_mux               16384  2 dwmac_sun8i
sunxi                  16384  0
phy_generic            20480  2 sunxi
```
