### ISSUE TITLE
Mass Storage Drive Emulation supported?

### ISSUE THREAD

**Issue by jhoff80** [srepac/kvmd-armbian#7]
Is Mass Storage Drive emulation supposed to be working with this installer?

I don't see the Drive menu in the web UI at all.  Running on a Pi4 with Geekworm KVM-A8 and Raspberry OS Lite (using this OS rather than Arch so that I can also run Proxmox Backup Server off the same Pi.

Just wondering if that's expected, or if something is wrong with my install.  I see the Drive menu with the official PiKVM builds.

**Comment by jhoff80** [comment]
Sorry, never mind, figured it out with the other scripts in the folder.

**Comment by shojkeee** [comment]
> Sorry, never mind, figured it out with the other scripts in the folder.

Hi. Hi. I can't start MSD. It's not even on the menu. Can you tell me how you managed to run it in this project?

**Comment by jhoff80** [comment]
> > Sorry, never mind, figured it out with the other scripts in the folder.
> 
> Hi. Hi. I can't start MSD. It's not even on the menu. Can you tell me how you managed to run it in this project?

You need to go to the kvmd-armbian folder which was created and run the flash-related script.
